# -*- coding: utf-8 -*-
"""PROJECT LOGISTIC REGRESSION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2U9QA9s4WxYVo1VE5w7bfL8pPfHVe4e
"""

y!git clone https://github.com/bpranjal/firstProjectECC.git     #clones the github repsitory

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/firstProjectECC/titanic_train.csv')

dataset.head()

sns.countplot('Sex',data = dataset)    #we get the rough estimate of number of males and females

sns.countplot('Pclass',data = dataset)    #number of people travelling in the classes

sns.countplot('Survived',data = dataset)   #0 represents dead and 1 represents alive

#countplot used when we have categiorical data(data having types)

sns.countplot('Embarked',data = dataset)   # s stands for southampton , Q for queenstown , C for cherbourg

sns.catplot('Pclass' , data=dataset ,hue='Survived',kind='count')    # no of people dead and alive in a partiular class

sns.boxplot(dataset.Age)    #it shows the density....the shaded part are called the outlier
plt.show

sns.boxplot(y=dataset.Fare)    #outliers need to be handled
plt.show

sns.distplot(dataset.Age)    #this data is quite normalized

sns.distplot(dataset.Fare)

sns.scatterplot(x=dataset.Age, y= dataset.Fare)

sns.heatmap(dataset.corr())

sns.pairplot(dataset)

